-- EDEX · Initial Users & Demo School Seed
-- Seed     : 002_core_initial_users_seed.sql
-- Purpose  : Seeds initial platform super_admin user and default demo school
--            (Delhi Public School) with school_admin user (principal_dps).
-- =============================================================================

-- 1. Create Super Admin User (school_id = NULL)
-- Password for superadmin: AdminPassword123!
-- bcrypt hash: $2a$10$w8uQZ0v1hY5o3c1YyWp4s.8T7G6m4Z3x1b2c3d4e5f6g7h8i9j0k1 (or dynamically generated by setup_db.js)

INSERT IGNORE INTO `core_users`
  (`user_id`, `school_id`, `username`, `email`, `phone`, `password_hash`, `is_active`)
VALUES
  ('00000000-0000-0000-0000-000000000001', NULL, 'superadmin', 'superadmin@edex.platform', '+919999900000', '$2a$10$wK8rXmFwL7Zp1B0O8iO3u.vA8T3E8Q0y7B8P6H8K5m2x7e1V0W4d2', TRUE);

-- Map super_admin role to superadmin user
INSERT IGNORE INTO `core_user_roles`
  (`user_role_id`, `user_id`, `role_id`, `school_id`)
SELECT
  '00000000-0000-0000-0000-000000000002',
  '00000000-0000-0000-0000-000000000001',
  r.role_id,
  NULL
FROM `core_roles` r
WHERE r.name = 'super_admin' AND r.school_id IS NULL
LIMIT 1;

-- 2. Create Default Demo School: Delhi Public School (DPS-DELHI)
INSERT IGNORE INTO `core_schools`
  (`school_id`, `name`, `code`, `address`, `city`, `state`, `country`, `phone`, `email`, `timezone`, `is_active`)
VALUES
  ('11111111-1111-1111-1111-111111111111', 'Delhi Public School', 'DPS-DELHI', 'Sector 12, R.K. Puram', 'New Delhi', 'Delhi', 'India', '+911126170051', 'info@dpsrkp.net', 'Asia/Kolkata', TRUE);

-- Activate default modules for DPS
INSERT IGNORE INTO `core_school_modules` (`school_module_id`, `school_id`, `module_name`, `is_enabled`)
VALUES
  (UUID(), '11111111-1111-1111-1111-111111111111', 'id_card', TRUE),
  (UUID(), '11111111-1111-1111-1111-111111111111', 'voting', TRUE),
  (UUID(), '11111111-1111-1111-1111-111111111111', 'bus', TRUE),
  (UUID(), '11111111-1111-1111-1111-111111111111', 'canteen', TRUE);

-- Seed Academic Year 2025-2026
INSERT IGNORE INTO `core_academic_years` (`academic_year_id`, `school_id`, `name`, `start_date`, `end_date`, `is_current`)
VALUES
  ('22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111', '2025-2026', '2025-04-01', '2026-03-31', TRUE);

-- Create School Admin user (principal_dps / PrincipalPass123!)
INSERT IGNORE INTO `core_users`
  (`user_id`, `school_id`, `username`, `email`, `phone`, `password_hash`, `is_active`)
VALUES
  ('33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 'principal_dps', 'principal@dpsrkp.net', '+919811122233', '$2a$10$tM2xK9Lp3N0vQ8wY7u.xA.v8b7n6m5l4k3j2h1g0f9d8s7a6z5y4x', TRUE);

-- Map school_admin role to principal_dps
INSERT IGNORE INTO `core_user_roles`
  (`user_role_id`, `user_id`, `role_id`, `school_id`)
SELECT
  '44444444-4444-4444-4444-444444444444',
  '33333333-3333-3333-3333-333333333333',
  r.role_id,
  '11111111-1111-1111-1111-111111111111'
FROM `core_roles` r
WHERE r.name = 'school_admin' AND r.school_id IS NULL
LIMIT 1;
